export const commonCarColors = [
  { name: "Noir", value: "Noir" },
  { name: "Blanc", value: "Blanc" },
  { name: "Gris", value: "Gris" },
  { name: "Gris Anthracite", value: "Gris Anthracite" },
  { name: "Argent", value: "Argent" },
  { name: "Bleu", value: "Bleu" },
  { name: "Bleu Marine", value: "Bleu Marine" },
  { name: "Rouge", value: "Rouge" },
  { name: "Bordeaux", value: "Bordeaux" },
  { name: "Vert", value: "Vert" },
  { name: "Vert Foncé", value: "Vert Foncé" },
  { name: "Jaune", value: "Jaune" },
  { name: "Orange", value: "Orange" },
  { name: "Marron", value: "Marron" },
  { name: "Beige", value: "Beige" },
  { name: "Or", value: "Or" },
  { name: "Bronze", value: "Bronze" },
  { name: "Violet", value: "Violet" },
  { name: "Rose", value: "Rose" },
];
