import type { Car } from "./types";

export const featuredCars: Car[] = [
  {
    id: "1",
    name: "CITROËN JUMPY",
    brand: "CITROËN",
    model: "JUMPY",
    year: "2024",
    price: "18 900",
    transmission: "Manuelle",
    fuel_type: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=CITROËN JUMPY",
  },
  {
    id: "2",
    name: "PEUGEOT RIFTER GT LINE",
    brand: "PEUGEOT",
    model: "RIFTER GT LINE",
    year: "2024",
    price: "19 500",
    transmission: "Manuelle",
    fuel_type: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=PEUGEOT RIFTER",
  },
  {
    id: "3",
    name: "RENAULT KWID",
    brand: "RENAULT",
    model: "KWID",
    year: "2024",
    price: "15 800",
    transmission: "Manuelle",
    fuel_type: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=RENAULT KWID",
  },
  {
    id: "4",
    name: "CITROËN BERLINGO",
    brand: "CITROËN",
    model: "BERLINGO",
    year: "2024",
    price: "18 900",
    transmission: "Manuelle",
    fuel: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=CITROËN BERLINGO",
  },
];

export const allCars: Car[] = [
  ...featuredCars,
  {
    id: "5",
    name: "RENAULT KANGOO",
    brand: "RENAULT",
    model: "KANGOO",
    year: "2024",
    price: "17 800",
    transmission: "Manuelle",
    fuel: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=RENAULT KANGOO",
  },
  {
    id: "6",
    name: "PEUGEOT TRAVELLER",
    brand: "PEUGEOT",
    model: "TRAVELLER",
    year: "2024",
    price: "24 500",
    transmission: "Automatique",
    fuel: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=PEUGEOT TRAVELLER",
  },
  {
    id: "7",
    name: "DACIA DUSTER",
    brand: "DACIA",
    model: "DUSTER",
    year: "2024",
    price: "16 900",
    transmission: "Automatique",
    fuel: "Diesel",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=DACIA DUSTER",
  },
  {
    id: "8",
    name: "PEUGEOT 208 ACTIVE",
    brand: "PEUGEOT",
    model: "208 ACTIVE",
    year: "2024",
    price: "15 500",
    transmission: "Automatique",
    fuel: "Essence",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=PEUGEOT 208",
  },
  {
    id: "9",
    name: "AUDI A3 ALLSTREET ESSENCE 35 TFSI 150CH EVA - EXPORT ALGÉRIE",
    brand: "AUDI",
    model: "A3 ALLSTREET",
    year: "2024",
    price: "30 000",
    transmission: "Automatique",
    fuel: "Essence",
    stock: "DISPONIBLE IMMÉDIATEMENT",
    image: "/placeholder.svg?height=200&width=300&text=AUDI A3",
  },
];
